name: CI/CD PIPELINE

on:
  push:
    branches:
      - main

jobs:
  read_from_file:
    runs-on: ubuntu-latest
    steps:
      - name: clone the project and redirect
        uses: actions/checkout@v2
      - name: read the file
        run : cat hello.txt
      - name: redirect to another folder and cat
        run : |
              cd test
              cat my_text.txt
      - name: install node js
        run : actions/setup-node@v6
      - name: make the file executable and run the script
        run : |
              chmod +x hello.sh
              ./hello.sh
      